// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	languagesFieldNames          = builder.RawFieldNames(&Languages{}, true)
	languagesRows                = strings.Join(languagesFieldNames, ",")
	languagesRowsExpectAutoSet   = strings.Join(stringx.Remove(languagesFieldNames, "data_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	languagesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(languagesFieldNames, "data_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cacheAnalysisLanguagesDataIdPrefix      = "cache:analysis:languages:dataId:"
	cacheAnalysisLanguagesDeveloperIdPrefix = "cache:analysis:languages:developerId:"
)

type (
	languagesModel interface {
		Insert(ctx context.Context, data *Languages) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*Languages, error)
		FindOneByDeveloperId(ctx context.Context, developerId int64) (*Languages, error)
		Update(ctx context.Context, data *Languages) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultLanguagesModel struct {
		sqlc.CachedConn
		table string
	}

	Languages struct {
		DataId        int64     `db:"data_id"`
		DataCreatedAt time.Time `db:"data_created_at"`
		DataUpdatedAt time.Time `db:"data_updated_at"`
		DeveloperId   int64     `db:"developer_id"`
		Languages     string    `db:"languages"`
	}
)

func newLanguagesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultLanguagesModel {
	return &defaultLanguagesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"analysis"."languages"`,
	}
}

func (m *defaultLanguagesModel) Delete(ctx context.Context, dataId int64) error {
	data, err := m.FindOne(ctx, dataId)
	if err != nil {
		return err
	}

	analysisLanguagesDataIdKey := fmt.Sprintf("%s%v", cacheAnalysisLanguagesDataIdPrefix, dataId)
	analysisLanguagesDeveloperIdKey := fmt.Sprintf("%s%v", cacheAnalysisLanguagesDeveloperIdPrefix, data.DeveloperId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where data_id = $1", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, analysisLanguagesDataIdKey, analysisLanguagesDeveloperIdKey)
	return err
}

func (m *defaultLanguagesModel) FindOne(ctx context.Context, dataId int64) (*Languages, error) {
	analysisLanguagesDataIdKey := fmt.Sprintf("%s%v", cacheAnalysisLanguagesDataIdPrefix, dataId)
	var resp Languages
	err := m.QueryRowCtx(ctx, &resp, analysisLanguagesDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where data_id = $1 limit 1", languagesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLanguagesModel) FindOneByDeveloperId(ctx context.Context, developerId int64) (*Languages, error) {
	analysisLanguagesDeveloperIdKey := fmt.Sprintf("%s%v", cacheAnalysisLanguagesDeveloperIdPrefix, developerId)
	var resp Languages
	err := m.QueryRowIndexCtx(ctx, &resp, analysisLanguagesDeveloperIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where developer_id = $1 limit 1", languagesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, developerId); err != nil {
			return nil, err
		}
		return resp.DataId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLanguagesModel) Insert(ctx context.Context, data *Languages) (sql.Result, error) {
	analysisLanguagesDataIdKey := fmt.Sprintf("%s%v", cacheAnalysisLanguagesDataIdPrefix, data.DataId)
	analysisLanguagesDeveloperIdKey := fmt.Sprintf("%s%v", cacheAnalysisLanguagesDeveloperIdPrefix, data.DeveloperId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, languagesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DataCreatedAt, data.DataUpdatedAt, data.DeveloperId, data.Languages)
	}, analysisLanguagesDataIdKey, analysisLanguagesDeveloperIdKey)
	return ret, err
}

func (m *defaultLanguagesModel) Update(ctx context.Context, newData *Languages) error {
	data, err := m.FindOne(ctx, newData.DataId)
	if err != nil {
		return err
	}

	analysisLanguagesDataIdKey := fmt.Sprintf("%s%v", cacheAnalysisLanguagesDataIdPrefix, data.DataId)
	analysisLanguagesDeveloperIdKey := fmt.Sprintf("%s%v", cacheAnalysisLanguagesDeveloperIdPrefix, data.DeveloperId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where data_id = $1", m.table, languagesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DataId, newData.DataCreatedAt, newData.DataUpdatedAt, newData.DeveloperId, newData.Languages)
	}, analysisLanguagesDataIdKey, analysisLanguagesDeveloperIdKey)
	return err
}

func (m *defaultLanguagesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAnalysisLanguagesDataIdPrefix, primary)
}

func (m *defaultLanguagesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where data_id = $1 limit 1", languagesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultLanguagesModel) tableName() string {
	return m.table
}
