// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	pulsePointFieldNames          = builder.RawFieldNames(&PulsePoint{}, true)
	pulsePointRows                = strings.Join(pulsePointFieldNames, ",")
	pulsePointRowsExpectAutoSet   = strings.Join(stringx.Remove(pulsePointFieldNames, "data_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	pulsePointRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(pulsePointFieldNames, "data_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cacheAnalysisPulsePointDataIdPrefix      = "cache:analysis:pulsePoint:dataId:"
	cacheAnalysisPulsePointDeveloperIdPrefix = "cache:analysis:pulsePoint:developerId:"
)

type (
	pulsePointModel interface {
		Insert(ctx context.Context, data *PulsePoint) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*PulsePoint, error)
		FindOneByDeveloperId(ctx context.Context, developerId int64) (*PulsePoint, error)
		Update(ctx context.Context, data *PulsePoint) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultPulsePointModel struct {
		sqlc.CachedConn
		table string
	}

	PulsePoint struct {
		DataId        int64     `db:"data_id"`
		DataCreatedAt time.Time `db:"data_created_at"`
		DataUpdatedAt time.Time `db:"data_updated_at"`
		DeveloperId   int64     `db:"developer_id"`
		PulsePoint    float64   `db:"pulse_point"`
	}
)

func newPulsePointModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPulsePointModel {
	return &defaultPulsePointModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"analysis"."pulse_point"`,
	}
}

func (m *defaultPulsePointModel) Delete(ctx context.Context, dataId int64) error {
	data, err := m.FindOne(ctx, dataId)
	if err != nil {
		return err
	}

	analysisPulsePointDataIdKey := fmt.Sprintf("%s%v", cacheAnalysisPulsePointDataIdPrefix, dataId)
	analysisPulsePointDeveloperIdKey := fmt.Sprintf("%s%v", cacheAnalysisPulsePointDeveloperIdPrefix, data.DeveloperId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where data_id = $1", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, analysisPulsePointDataIdKey, analysisPulsePointDeveloperIdKey)
	return err
}

func (m *defaultPulsePointModel) FindOne(ctx context.Context, dataId int64) (*PulsePoint, error) {
	analysisPulsePointDataIdKey := fmt.Sprintf("%s%v", cacheAnalysisPulsePointDataIdPrefix, dataId)
	var resp PulsePoint
	err := m.QueryRowCtx(ctx, &resp, analysisPulsePointDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where data_id = $1 limit 1", pulsePointRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPulsePointModel) FindOneByDeveloperId(ctx context.Context, developerId int64) (*PulsePoint, error) {
	analysisPulsePointDeveloperIdKey := fmt.Sprintf("%s%v", cacheAnalysisPulsePointDeveloperIdPrefix, developerId)
	var resp PulsePoint
	err := m.QueryRowIndexCtx(ctx, &resp, analysisPulsePointDeveloperIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where developer_id = $1 limit 1", pulsePointRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, developerId); err != nil {
			return nil, err
		}
		return resp.DataId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPulsePointModel) Insert(ctx context.Context, data *PulsePoint) (sql.Result, error) {
	analysisPulsePointDataIdKey := fmt.Sprintf("%s%v", cacheAnalysisPulsePointDataIdPrefix, data.DataId)
	analysisPulsePointDeveloperIdKey := fmt.Sprintf("%s%v", cacheAnalysisPulsePointDeveloperIdPrefix, data.DeveloperId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, pulsePointRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DataCreatedAt, data.DataUpdatedAt, data.DeveloperId, data.PulsePoint)
	}, analysisPulsePointDataIdKey, analysisPulsePointDeveloperIdKey)
	return ret, err
}

func (m *defaultPulsePointModel) Update(ctx context.Context, newData *PulsePoint) error {
	data, err := m.FindOne(ctx, newData.DataId)
	if err != nil {
		return err
	}

	analysisPulsePointDataIdKey := fmt.Sprintf("%s%v", cacheAnalysisPulsePointDataIdPrefix, data.DataId)
	analysisPulsePointDeveloperIdKey := fmt.Sprintf("%s%v", cacheAnalysisPulsePointDeveloperIdPrefix, data.DeveloperId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where data_id = $1", m.table, pulsePointRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DataId, newData.DataCreatedAt, newData.DataUpdatedAt, newData.DeveloperId, newData.PulsePoint)
	}, analysisPulsePointDataIdKey, analysisPulsePointDeveloperIdKey)
	return err
}

func (m *defaultPulsePointModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAnalysisPulsePointDataIdPrefix, primary)
}

func (m *defaultPulsePointModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where data_id = $1 limit 1", pulsePointRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPulsePointModel) tableName() string {
	return m.table
}
