// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: idGenerator.proto

package idgenerator

import (
	"context"

	"github.com/ShellWen/GitPulse/id_generator/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetIdReq  = pb.GetIdReq
	GetIdResp = pb.GetIdResp

	IdGenerator interface {
		GetId(ctx context.Context, in *GetIdReq, opts ...grpc.CallOption) (*GetIdResp, error)
	}

	defaultIdGenerator struct {
		cli zrpc.Client
	}
)

func NewIdGenerator(cli zrpc.Client) IdGenerator {
	return &defaultIdGenerator{
		cli: cli,
	}
}

func (m *defaultIdGenerator) GetId(ctx context.Context, in *GetIdReq, opts ...grpc.CallOption) (*GetIdResp, error) {
	client := pb.NewIdGeneratorClient(m.cli.Conn())
	return client.GetId(ctx, in, opts...)
}
