// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type GetDeveloperReq struct {
	Login string `path:"login"`
}

type GetDeveloperResp struct {
	Id        int64  `json:"id"`
	Name      string `json:"name"`
	Login     string `json:"login"`
	AvatarUrl string `json:"avatar_url"`
	Company   string `json:"company"`
	Location  string `json:"location"`
	Bio       string `json:"bio"`
	Blog      string `json:"blog"`
	Email     string `json:"email"`
	Followers int64  `json:"followers"`
	Following int64  `json:"following"`
	Stars     int64  `json:"stars"`
	Repos     int64  `json:"repos"`
	Gists     int64  `json:"gists"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}
