// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type GetDeveloperReq struct {
	Username string `path:"login"`
}

type GetDeveloperResp struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
	Data    struct {
		Id        int64  `json:"id"`
		Name      string `json:"name"`
		Username  string `json:"login"`
		AvatarUrl string `json:"avatar_url"`
		Company   string `json:"company"`
		Location  string `json:"location"`
		Bio       string `json:"bio"`
		Blog      string `json:"blog"`
		Email     string `json:"email"`
		CreateAt  string `json:"created_at"`
		UpdateAt  string `json:"updated_at"`
	} `json:"data"`
}
