// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	createRepoFieldNames          = builder.RawFieldNames(&CreateRepo{}, true)
	createRepoRows                = strings.Join(createRepoFieldNames, ",")
	createRepoRowsExpectAutoSet   = strings.Join(stringx.Remove(createRepoFieldNames, "data_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	createRepoRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(createRepoFieldNames, "data_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cacheRelationCreateRepoDataIdPrefix = "cache:relation:createRepo:dataId:"
	cacheRelationCreateRepoRepoIdPrefix = "cache:relation:createRepo:repoId:"
)

type (
	createRepoModel interface {
		Insert(ctx context.Context, data *CreateRepo) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*CreateRepo, error)
		FindOneByRepoId(ctx context.Context, repoId int64) (*CreateRepo, error)
		Update(ctx context.Context, data *CreateRepo) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultCreateRepoModel struct {
		sqlc.CachedConn
		table string
	}

	CreateRepo struct {
		DataId       int64     `db:"data_id"`
		DataCreateAt time.Time `db:"data_create_at"`
		DataUpdateAt time.Time `db:"data_update_at"`
		DeveloperId  int64     `db:"developer_id"`
		RepoId       int64     `db:"repo_id"`
	}
)

func newCreateRepoModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCreateRepoModel {
	return &defaultCreateRepoModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"relation"."create_repo"`,
	}
}

func (m *defaultCreateRepoModel) Delete(ctx context.Context, dataId int64) error {
	data, err := m.FindOne(ctx, dataId)
	if err != nil {
		return err
	}

	relationCreateRepoDataIdKey := fmt.Sprintf("%s%v", cacheRelationCreateRepoDataIdPrefix, dataId)
	relationCreateRepoRepoIdKey := fmt.Sprintf("%s%v", cacheRelationCreateRepoRepoIdPrefix, data.RepoId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where data_id = $1", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, relationCreateRepoDataIdKey, relationCreateRepoRepoIdKey)
	return err
}

func (m *defaultCreateRepoModel) FindOne(ctx context.Context, dataId int64) (*CreateRepo, error) {
	relationCreateRepoDataIdKey := fmt.Sprintf("%s%v", cacheRelationCreateRepoDataIdPrefix, dataId)
	var resp CreateRepo
	err := m.QueryRowCtx(ctx, &resp, relationCreateRepoDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where data_id = $1 limit 1", createRepoRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCreateRepoModel) FindOneByRepoId(ctx context.Context, repoId int64) (*CreateRepo, error) {
	relationCreateRepoRepoIdKey := fmt.Sprintf("%s%v", cacheRelationCreateRepoRepoIdPrefix, repoId)
	var resp CreateRepo
	err := m.QueryRowIndexCtx(ctx, &resp, relationCreateRepoRepoIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where repo_id = $1 limit 1", createRepoRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, repoId); err != nil {
			return nil, err
		}
		return resp.DataId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCreateRepoModel) Insert(ctx context.Context, data *CreateRepo) (sql.Result, error) {
	relationCreateRepoDataIdKey := fmt.Sprintf("%s%v", cacheRelationCreateRepoDataIdPrefix, data.DataId)
	relationCreateRepoRepoIdKey := fmt.Sprintf("%s%v", cacheRelationCreateRepoRepoIdPrefix, data.RepoId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, createRepoRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DataCreateAt, data.DataUpdateAt, data.DeveloperId, data.RepoId)
	}, relationCreateRepoDataIdKey, relationCreateRepoRepoIdKey)
	return ret, err
}

func (m *defaultCreateRepoModel) Update(ctx context.Context, newData *CreateRepo) error {
	data, err := m.FindOne(ctx, newData.DataId)
	if err != nil {
		return err
	}

	relationCreateRepoDataIdKey := fmt.Sprintf("%s%v", cacheRelationCreateRepoDataIdPrefix, data.DataId)
	relationCreateRepoRepoIdKey := fmt.Sprintf("%s%v", cacheRelationCreateRepoRepoIdPrefix, data.RepoId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where data_id = $1", m.table, createRepoRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DataId, newData.DataCreateAt, newData.DataUpdateAt, newData.DeveloperId, newData.RepoId)
	}, relationCreateRepoDataIdKey, relationCreateRepoRepoIdKey)
	return err
}

func (m *defaultCreateRepoModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRelationCreateRepoDataIdPrefix, primary)
}

func (m *defaultCreateRepoModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where data_id = $1 limit 1", createRepoRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCreateRepoModel) tableName() string {
	return m.table
}
