// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	forkFieldNames          = builder.RawFieldNames(&Fork{}, true)
	forkRows                = strings.Join(forkFieldNames, ",")
	forkRowsExpectAutoSet   = strings.Join(stringx.Remove(forkFieldNames, "data_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	forkRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(forkFieldNames, "data_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cacheRelationForkDataIdPrefix     = "cache:relation:fork:dataId:"
	cacheRelationForkForkRepoIdPrefix = "cache:relation:fork:forkRepoId:"
)

type (
	forkModel interface {
		Insert(ctx context.Context, data *Fork) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*Fork, error)
		FindOneByForkRepoId(ctx context.Context, forkRepoId int64) (*Fork, error)
		Update(ctx context.Context, data *Fork) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultForkModel struct {
		sqlc.CachedConn
		table string
	}

	Fork struct {
		DataId         int64     `db:"data_id"`
		DataCreateAt   time.Time `db:"data_create_at"`
		DataUpdateAt   time.Time `db:"data_update_at"`
		OriginalRepoId int64     `db:"original_repo_id"`
		ForkRepoId     int64     `db:"fork_repo_id"`
	}
)

func newForkModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultForkModel {
	return &defaultForkModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"relation"."fork"`,
	}
}

func (m *defaultForkModel) Delete(ctx context.Context, dataId int64) error {
	data, err := m.FindOne(ctx, dataId)
	if err != nil {
		return err
	}

	relationForkDataIdKey := fmt.Sprintf("%s%v", cacheRelationForkDataIdPrefix, dataId)
	relationForkForkRepoIdKey := fmt.Sprintf("%s%v", cacheRelationForkForkRepoIdPrefix, data.ForkRepoId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where data_id = $1", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, relationForkDataIdKey, relationForkForkRepoIdKey)
	return err
}

func (m *defaultForkModel) FindOne(ctx context.Context, dataId int64) (*Fork, error) {
	relationForkDataIdKey := fmt.Sprintf("%s%v", cacheRelationForkDataIdPrefix, dataId)
	var resp Fork
	err := m.QueryRowCtx(ctx, &resp, relationForkDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where data_id = $1 limit 1", forkRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForkModel) FindOneByForkRepoId(ctx context.Context, forkRepoId int64) (*Fork, error) {
	relationForkForkRepoIdKey := fmt.Sprintf("%s%v", cacheRelationForkForkRepoIdPrefix, forkRepoId)
	var resp Fork
	err := m.QueryRowIndexCtx(ctx, &resp, relationForkForkRepoIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where fork_repo_id = $1 limit 1", forkRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, forkRepoId); err != nil {
			return nil, err
		}
		return resp.DataId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForkModel) Insert(ctx context.Context, data *Fork) (sql.Result, error) {
	relationForkDataIdKey := fmt.Sprintf("%s%v", cacheRelationForkDataIdPrefix, data.DataId)
	relationForkForkRepoIdKey := fmt.Sprintf("%s%v", cacheRelationForkForkRepoIdPrefix, data.ForkRepoId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, forkRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DataCreateAt, data.DataUpdateAt, data.OriginalRepoId, data.ForkRepoId)
	}, relationForkDataIdKey, relationForkForkRepoIdKey)
	return ret, err
}

func (m *defaultForkModel) Update(ctx context.Context, newData *Fork) error {
	data, err := m.FindOne(ctx, newData.DataId)
	if err != nil {
		return err
	}

	relationForkDataIdKey := fmt.Sprintf("%s%v", cacheRelationForkDataIdPrefix, data.DataId)
	relationForkForkRepoIdKey := fmt.Sprintf("%s%v", cacheRelationForkForkRepoIdPrefix, data.ForkRepoId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where data_id = $1", m.table, forkRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DataId, newData.DataCreateAt, newData.DataUpdateAt, newData.OriginalRepoId, newData.ForkRepoId)
	}, relationForkDataIdKey, relationForkForkRepoIdKey)
	return err
}

func (m *defaultForkModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRelationForkDataIdPrefix, primary)
}

func (m *defaultForkModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where data_id = $1 limit 1", forkRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultForkModel) tableName() string {
	return m.table
}
