// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	forkUpdatedAtFieldNames          = builder.RawFieldNames(&ForkUpdatedAt{}, true)
	forkUpdatedAtRows                = strings.Join(forkUpdatedAtFieldNames, ",")
	forkUpdatedAtRowsExpectAutoSet   = strings.Join(stringx.Remove(forkUpdatedAtFieldNames, "data_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	forkUpdatedAtRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(forkUpdatedAtFieldNames, "data_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cacheRelationForkUpdatedAtDataIdPrefix = "cache:relation:forkUpdatedAt:dataId:"
	cacheRelationForkUpdatedAtRepoIdPrefix = "cache:relation:forkUpdatedAt:repoId:"
)

type (
	forkUpdatedAtModel interface {
		Insert(ctx context.Context, data *ForkUpdatedAt) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*ForkUpdatedAt, error)
		FindOneByRepoId(ctx context.Context, repoId int64) (*ForkUpdatedAt, error)
		Update(ctx context.Context, data *ForkUpdatedAt) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultForkUpdatedAtModel struct {
		sqlc.CachedConn
		table string
	}

	ForkUpdatedAt struct {
		DataId    int64     `db:"data_id"`
		RepoId    int64     `db:"repo_id"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newForkUpdatedAtModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultForkUpdatedAtModel {
	return &defaultForkUpdatedAtModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"relation"."fork_updated_at"`,
	}
}

func (m *defaultForkUpdatedAtModel) Delete(ctx context.Context, dataId int64) error {
	data, err := m.FindOne(ctx, dataId)
	if err != nil {
		return err
	}

	relationForkUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheRelationForkUpdatedAtDataIdPrefix, dataId)
	relationForkUpdatedAtRepoIdKey := fmt.Sprintf("%s%v", cacheRelationForkUpdatedAtRepoIdPrefix, data.RepoId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where data_id = $1", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, relationForkUpdatedAtDataIdKey, relationForkUpdatedAtRepoIdKey)
	return err
}

func (m *defaultForkUpdatedAtModel) FindOne(ctx context.Context, dataId int64) (*ForkUpdatedAt, error) {
	relationForkUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheRelationForkUpdatedAtDataIdPrefix, dataId)
	var resp ForkUpdatedAt
	err := m.QueryRowCtx(ctx, &resp, relationForkUpdatedAtDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where data_id = $1 limit 1", forkUpdatedAtRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForkUpdatedAtModel) FindOneByRepoId(ctx context.Context, repoId int64) (*ForkUpdatedAt, error) {
	relationForkUpdatedAtRepoIdKey := fmt.Sprintf("%s%v", cacheRelationForkUpdatedAtRepoIdPrefix, repoId)
	var resp ForkUpdatedAt
	err := m.QueryRowIndexCtx(ctx, &resp, relationForkUpdatedAtRepoIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where repo_id = $1 limit 1", forkUpdatedAtRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, repoId); err != nil {
			return nil, err
		}
		return resp.DataId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultForkUpdatedAtModel) Insert(ctx context.Context, data *ForkUpdatedAt) (sql.Result, error) {
	relationForkUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheRelationForkUpdatedAtDataIdPrefix, data.DataId)
	relationForkUpdatedAtRepoIdKey := fmt.Sprintf("%s%v", cacheRelationForkUpdatedAtRepoIdPrefix, data.RepoId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1)", m.table, forkUpdatedAtRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RepoId)
	}, relationForkUpdatedAtDataIdKey, relationForkUpdatedAtRepoIdKey)
	return ret, err
}

func (m *defaultForkUpdatedAtModel) Update(ctx context.Context, newData *ForkUpdatedAt) error {
	data, err := m.FindOne(ctx, newData.DataId)
	if err != nil {
		return err
	}

	relationForkUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheRelationForkUpdatedAtDataIdPrefix, data.DataId)
	relationForkUpdatedAtRepoIdKey := fmt.Sprintf("%s%v", cacheRelationForkUpdatedAtRepoIdPrefix, data.RepoId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where data_id = $1", m.table, forkUpdatedAtRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DataId, newData.RepoId)
	}, relationForkUpdatedAtDataIdKey, relationForkUpdatedAtRepoIdKey)
	return err
}

func (m *defaultForkUpdatedAtModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRelationForkUpdatedAtDataIdPrefix, primary)
}

func (m *defaultForkUpdatedAtModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where data_id = $1 limit 1", forkUpdatedAtRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultForkUpdatedAtModel) tableName() string {
	return m.table
}
