// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	starredRepoUpdatedAtFieldNames          = builder.RawFieldNames(&StarredRepoUpdatedAt{}, true)
	starredRepoUpdatedAtRows                = strings.Join(starredRepoUpdatedAtFieldNames, ",")
	starredRepoUpdatedAtRowsExpectAutoSet   = strings.Join(stringx.Remove(starredRepoUpdatedAtFieldNames, "data_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	starredRepoUpdatedAtRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(starredRepoUpdatedAtFieldNames, "data_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cacheRelationStarredRepoUpdatedAtDataIdPrefix      = "cache:relation:starredRepoUpdatedAt:dataId:"
	cacheRelationStarredRepoUpdatedAtDeveloperIdPrefix = "cache:relation:starredRepoUpdatedAt:developerId:"
)

type (
	starredRepoUpdatedAtModel interface {
		Insert(ctx context.Context, data *StarredRepoUpdatedAt) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*StarredRepoUpdatedAt, error)
		FindOneByDeveloperId(ctx context.Context, developerId int64) (*StarredRepoUpdatedAt, error)
		Update(ctx context.Context, data *StarredRepoUpdatedAt) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultStarredRepoUpdatedAtModel struct {
		sqlc.CachedConn
		table string
	}

	StarredRepoUpdatedAt struct {
		DataId      int64     `db:"data_id"`
		DeveloperId int64     `db:"developer_id"`
		UpdatedAt   time.Time `db:"updated_at"`
	}
)

func newStarredRepoUpdatedAtModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultStarredRepoUpdatedAtModel {
	return &defaultStarredRepoUpdatedAtModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"relation"."starred_repo_updated_at"`,
	}
}

func (m *defaultStarredRepoUpdatedAtModel) Delete(ctx context.Context, dataId int64) error {
	data, err := m.FindOne(ctx, dataId)
	if err != nil {
		return err
	}

	relationStarredRepoUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheRelationStarredRepoUpdatedAtDataIdPrefix, dataId)
	relationStarredRepoUpdatedAtDeveloperIdKey := fmt.Sprintf("%s%v", cacheRelationStarredRepoUpdatedAtDeveloperIdPrefix, data.DeveloperId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where data_id = $1", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, relationStarredRepoUpdatedAtDataIdKey, relationStarredRepoUpdatedAtDeveloperIdKey)
	return err
}

func (m *defaultStarredRepoUpdatedAtModel) FindOne(ctx context.Context, dataId int64) (*StarredRepoUpdatedAt, error) {
	relationStarredRepoUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheRelationStarredRepoUpdatedAtDataIdPrefix, dataId)
	var resp StarredRepoUpdatedAt
	err := m.QueryRowCtx(ctx, &resp, relationStarredRepoUpdatedAtDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where data_id = $1 limit 1", starredRepoUpdatedAtRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStarredRepoUpdatedAtModel) FindOneByDeveloperId(ctx context.Context, developerId int64) (*StarredRepoUpdatedAt, error) {
	relationStarredRepoUpdatedAtDeveloperIdKey := fmt.Sprintf("%s%v", cacheRelationStarredRepoUpdatedAtDeveloperIdPrefix, developerId)
	var resp StarredRepoUpdatedAt
	err := m.QueryRowIndexCtx(ctx, &resp, relationStarredRepoUpdatedAtDeveloperIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where developer_id = $1 limit 1", starredRepoUpdatedAtRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, developerId); err != nil {
			return nil, err
		}
		return resp.DataId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStarredRepoUpdatedAtModel) Insert(ctx context.Context, data *StarredRepoUpdatedAt) (sql.Result, error) {
	relationStarredRepoUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheRelationStarredRepoUpdatedAtDataIdPrefix, data.DataId)
	relationStarredRepoUpdatedAtDeveloperIdKey := fmt.Sprintf("%s%v", cacheRelationStarredRepoUpdatedAtDeveloperIdPrefix, data.DeveloperId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1)", m.table, starredRepoUpdatedAtRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DeveloperId)
	}, relationStarredRepoUpdatedAtDataIdKey, relationStarredRepoUpdatedAtDeveloperIdKey)
	return ret, err
}

func (m *defaultStarredRepoUpdatedAtModel) Update(ctx context.Context, newData *StarredRepoUpdatedAt) error {
	data, err := m.FindOne(ctx, newData.DataId)
	if err != nil {
		return err
	}

	relationStarredRepoUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheRelationStarredRepoUpdatedAtDataIdPrefix, data.DataId)
	relationStarredRepoUpdatedAtDeveloperIdKey := fmt.Sprintf("%s%v", cacheRelationStarredRepoUpdatedAtDeveloperIdPrefix, data.DeveloperId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where data_id = $1", m.table, starredRepoUpdatedAtRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DataId, newData.DeveloperId)
	}, relationStarredRepoUpdatedAtDataIdKey, relationStarredRepoUpdatedAtDeveloperIdKey)
	return err
}

func (m *defaultStarredRepoUpdatedAtModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRelationStarredRepoUpdatedAtDataIdPrefix, primary)
}

func (m *defaultStarredRepoUpdatedAtModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where data_id = $1 limit 1", starredRepoUpdatedAtRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultStarredRepoUpdatedAtModel) tableName() string {
	return m.table
}
