// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: analysis.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Analysis_AddAnalysis_FullMethodName    = "/pb.analysis/AddAnalysis"
	Analysis_UpdateAnalysis_FullMethodName = "/pb.analysis/UpdateAnalysis"
	Analysis_DelAnalysis_FullMethodName    = "/pb.analysis/DelAnalysis"
	Analysis_GetAnalysis_FullMethodName    = "/pb.analysis/GetAnalysis"
)

// AnalysisClient is the client API for Analysis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalysisClient interface {
	// -----------------------analysis-----------------------
	AddAnalysis(ctx context.Context, in *AddAnalysisReq, opts ...grpc.CallOption) (*AddAnalysisResp, error)
	UpdateAnalysis(ctx context.Context, in *UpdateAnalysisReq, opts ...grpc.CallOption) (*UpdateAnalysisResp, error)
	DelAnalysis(ctx context.Context, in *DelAnalysisReq, opts ...grpc.CallOption) (*DelAnalysisResp, error)
	GetAnalysis(ctx context.Context, in *GetAnalysisReq, opts ...grpc.CallOption) (*GetAnalysisResp, error)
}

type analysisClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalysisClient(cc grpc.ClientConnInterface) AnalysisClient {
	return &analysisClient{cc}
}

func (c *analysisClient) AddAnalysis(ctx context.Context, in *AddAnalysisReq, opts ...grpc.CallOption) (*AddAnalysisResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAnalysisResp)
	err := c.cc.Invoke(ctx, Analysis_AddAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisClient) UpdateAnalysis(ctx context.Context, in *UpdateAnalysisReq, opts ...grpc.CallOption) (*UpdateAnalysisResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAnalysisResp)
	err := c.cc.Invoke(ctx, Analysis_UpdateAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisClient) DelAnalysis(ctx context.Context, in *DelAnalysisReq, opts ...grpc.CallOption) (*DelAnalysisResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelAnalysisResp)
	err := c.cc.Invoke(ctx, Analysis_DelAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisClient) GetAnalysis(ctx context.Context, in *GetAnalysisReq, opts ...grpc.CallOption) (*GetAnalysisResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnalysisResp)
	err := c.cc.Invoke(ctx, Analysis_GetAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalysisServer is the server API for Analysis service.
// All implementations must embed UnimplementedAnalysisServer
// for forward compatibility.
type AnalysisServer interface {
	// -----------------------analysis-----------------------
	AddAnalysis(context.Context, *AddAnalysisReq) (*AddAnalysisResp, error)
	UpdateAnalysis(context.Context, *UpdateAnalysisReq) (*UpdateAnalysisResp, error)
	DelAnalysis(context.Context, *DelAnalysisReq) (*DelAnalysisResp, error)
	GetAnalysis(context.Context, *GetAnalysisReq) (*GetAnalysisResp, error)
	mustEmbedUnimplementedAnalysisServer()
}

// UnimplementedAnalysisServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalysisServer struct{}

func (UnimplementedAnalysisServer) AddAnalysis(context.Context, *AddAnalysisReq) (*AddAnalysisResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAnalysis not implemented")
}
func (UnimplementedAnalysisServer) UpdateAnalysis(context.Context, *UpdateAnalysisReq) (*UpdateAnalysisResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAnalysis not implemented")
}
func (UnimplementedAnalysisServer) DelAnalysis(context.Context, *DelAnalysisReq) (*DelAnalysisResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelAnalysis not implemented")
}
func (UnimplementedAnalysisServer) GetAnalysis(context.Context, *GetAnalysisReq) (*GetAnalysisResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnalysis not implemented")
}
func (UnimplementedAnalysisServer) mustEmbedUnimplementedAnalysisServer() {}
func (UnimplementedAnalysisServer) testEmbeddedByValue()                  {}

// UnsafeAnalysisServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalysisServer will
// result in compilation errors.
type UnsafeAnalysisServer interface {
	mustEmbedUnimplementedAnalysisServer()
}

func RegisterAnalysisServer(s grpc.ServiceRegistrar, srv AnalysisServer) {
	// If the following call pancis, it indicates UnimplementedAnalysisServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Analysis_ServiceDesc, srv)
}

func _Analysis_AddAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAnalysisReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServer).AddAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Analysis_AddAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServer).AddAnalysis(ctx, req.(*AddAnalysisReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analysis_UpdateAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAnalysisReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServer).UpdateAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Analysis_UpdateAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServer).UpdateAnalysis(ctx, req.(*UpdateAnalysisReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analysis_DelAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelAnalysisReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServer).DelAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Analysis_DelAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServer).DelAnalysis(ctx, req.(*DelAnalysisReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analysis_GetAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnalysisReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServer).GetAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Analysis_GetAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServer).GetAnalysis(ctx, req.(*GetAnalysisReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Analysis_ServiceDesc is the grpc.ServiceDesc for Analysis service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Analysis_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.analysis",
	HandlerType: (*AnalysisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAnalysis",
			Handler:    _Analysis_AddAnalysis_Handler,
		},
		{
			MethodName: "UpdateAnalysis",
			Handler:    _Analysis_UpdateAnalysis_Handler,
		},
		{
			MethodName: "DelAnalysis",
			Handler:    _Analysis_DelAnalysis_Handler,
		},
		{
			MethodName: "GetAnalysis",
			Handler:    _Analysis_GetAnalysis_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analysis.proto",
}
