// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.19.4
// source: analysis.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------------------------analysis--------------------------------
type Analysis struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataId       int64   `protobuf:"varint,1,opt,name=dataId,proto3" json:"dataId,omitempty"`             //dataId
	DataCreateAt int64   `protobuf:"varint,2,opt,name=dataCreateAt,proto3" json:"dataCreateAt,omitempty"` //dataCreateAt
	DataUpdateAt int64   `protobuf:"varint,3,opt,name=dataUpdateAt,proto3" json:"dataUpdateAt,omitempty"` //dataUpdateAt
	Languages    string  `protobuf:"bytes,4,opt,name=languages,proto3" json:"languages,omitempty"`        //languages
	TalentRank   float64 `protobuf:"fixed64,5,opt,name=talentRank,proto3" json:"talentRank,omitempty"`    //talentRank
	DeveloperId  int64   `protobuf:"varint,6,opt,name=developerId,proto3" json:"developerId,omitempty"`   //developerId
	Nation       string  `protobuf:"bytes,7,opt,name=nation,proto3" json:"nation,omitempty"`              //nation
}

func (x *Analysis) Reset() {
	*x = Analysis{}
	mi := &file_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Analysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Analysis) ProtoMessage() {}

func (x *Analysis) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Analysis.ProtoReflect.Descriptor instead.
func (*Analysis) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *Analysis) GetDataId() int64 {
	if x != nil {
		return x.DataId
	}
	return 0
}

func (x *Analysis) GetDataCreateAt() int64 {
	if x != nil {
		return x.DataCreateAt
	}
	return 0
}

func (x *Analysis) GetDataUpdateAt() int64 {
	if x != nil {
		return x.DataUpdateAt
	}
	return 0
}

func (x *Analysis) GetLanguages() string {
	if x != nil {
		return x.Languages
	}
	return ""
}

func (x *Analysis) GetTalentRank() float64 {
	if x != nil {
		return x.TalentRank
	}
	return 0
}

func (x *Analysis) GetDeveloperId() int64 {
	if x != nil {
		return x.DeveloperId
	}
	return 0
}

func (x *Analysis) GetNation() string {
	if x != nil {
		return x.Nation
	}
	return ""
}

type AddAnalysisReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Languages   string  `protobuf:"bytes,1,opt,name=languages,proto3" json:"languages,omitempty"`      //languages
	TalentRank  float64 `protobuf:"fixed64,2,opt,name=talentRank,proto3" json:"talentRank,omitempty"`  //talentRank
	DeveloperId int64   `protobuf:"varint,3,opt,name=developerId,proto3" json:"developerId,omitempty"` //developerId
	Nation      string  `protobuf:"bytes,4,opt,name=nation,proto3" json:"nation,omitempty"`            //nation
}

func (x *AddAnalysisReq) Reset() {
	*x = AddAnalysisReq{}
	mi := &file_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAnalysisReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAnalysisReq) ProtoMessage() {}

func (x *AddAnalysisReq) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAnalysisReq.ProtoReflect.Descriptor instead.
func (*AddAnalysisReq) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *AddAnalysisReq) GetLanguages() string {
	if x != nil {
		return x.Languages
	}
	return ""
}

func (x *AddAnalysisReq) GetTalentRank() float64 {
	if x != nil {
		return x.TalentRank
	}
	return 0
}

func (x *AddAnalysisReq) GetDeveloperId() int64 {
	if x != nil {
		return x.DeveloperId
	}
	return 0
}

func (x *AddAnalysisReq) GetNation() string {
	if x != nil {
		return x.Nation
	}
	return ""
}

type AddAnalysisResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddAnalysisResp) Reset() {
	*x = AddAnalysisResp{}
	mi := &file_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAnalysisResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAnalysisResp) ProtoMessage() {}

func (x *AddAnalysisResp) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAnalysisResp.ProtoReflect.Descriptor instead.
func (*AddAnalysisResp) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{2}
}

type UpdateAnalysisReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Languages   string  `protobuf:"bytes,1,opt,name=languages,proto3" json:"languages,omitempty"`      //languages
	TalentRank  float64 `protobuf:"fixed64,2,opt,name=talentRank,proto3" json:"talentRank,omitempty"`  //talentRank
	DeveloperId int64   `protobuf:"varint,3,opt,name=developerId,proto3" json:"developerId,omitempty"` //developerId
	Nation      string  `protobuf:"bytes,4,opt,name=nation,proto3" json:"nation,omitempty"`            //nation
}

func (x *UpdateAnalysisReq) Reset() {
	*x = UpdateAnalysisReq{}
	mi := &file_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnalysisReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnalysisReq) ProtoMessage() {}

func (x *UpdateAnalysisReq) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnalysisReq.ProtoReflect.Descriptor instead.
func (*UpdateAnalysisReq) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAnalysisReq) GetLanguages() string {
	if x != nil {
		return x.Languages
	}
	return ""
}

func (x *UpdateAnalysisReq) GetTalentRank() float64 {
	if x != nil {
		return x.TalentRank
	}
	return 0
}

func (x *UpdateAnalysisReq) GetDeveloperId() int64 {
	if x != nil {
		return x.DeveloperId
	}
	return 0
}

func (x *UpdateAnalysisReq) GetNation() string {
	if x != nil {
		return x.Nation
	}
	return ""
}

type UpdateAnalysisResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAnalysisResp) Reset() {
	*x = UpdateAnalysisResp{}
	mi := &file_analysis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnalysisResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnalysisResp) ProtoMessage() {}

func (x *UpdateAnalysisResp) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnalysisResp.ProtoReflect.Descriptor instead.
func (*UpdateAnalysisResp) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{4}
}

type DelAnalysisReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeveloperId int64 `protobuf:"varint,1,opt,name=developerId,proto3" json:"developerId,omitempty"` //developerId
}

func (x *DelAnalysisReq) Reset() {
	*x = DelAnalysisReq{}
	mi := &file_analysis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelAnalysisReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelAnalysisReq) ProtoMessage() {}

func (x *DelAnalysisReq) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelAnalysisReq.ProtoReflect.Descriptor instead.
func (*DelAnalysisReq) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{5}
}

func (x *DelAnalysisReq) GetDeveloperId() int64 {
	if x != nil {
		return x.DeveloperId
	}
	return 0
}

type DelAnalysisResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelAnalysisResp) Reset() {
	*x = DelAnalysisResp{}
	mi := &file_analysis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelAnalysisResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelAnalysisResp) ProtoMessage() {}

func (x *DelAnalysisResp) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelAnalysisResp.ProtoReflect.Descriptor instead.
func (*DelAnalysisResp) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{6}
}

type GetAnalysisReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeveloperId int64 `protobuf:"varint,1,opt,name=developerId,proto3" json:"developerId,omitempty"` //developerId
}

func (x *GetAnalysisReq) Reset() {
	*x = GetAnalysisReq{}
	mi := &file_analysis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisReq) ProtoMessage() {}

func (x *GetAnalysisReq) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisReq.ProtoReflect.Descriptor instead.
func (*GetAnalysisReq) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{7}
}

func (x *GetAnalysisReq) GetDeveloperId() int64 {
	if x != nil {
		return x.DeveloperId
	}
	return 0
}

type GetAnalysisResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Analysis *Analysis `protobuf:"bytes,1,opt,name=analysis,proto3" json:"analysis,omitempty"` //analysis
}

func (x *GetAnalysisResp) Reset() {
	*x = GetAnalysisResp{}
	mi := &file_analysis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisResp) ProtoMessage() {}

func (x *GetAnalysisResp) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisResp.ProtoReflect.Descriptor instead.
func (*GetAnalysisResp) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{8}
}

func (x *GetAnalysisResp) GetAnalysis() *Analysis {
	if x != nil {
		return x.Analysis
	}
	return nil
}

var File_analysis_proto protoreflect.FileDescriptor

var file_analysis_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0xe2, 0x01, 0x0a, 0x08, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x74, 0x61, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x64, 0x61, 0x74, 0x61, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x61, 0x74,
	0x61, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0c, 0x64, 0x61, 0x74, 0x61, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x22, 0x0a,
	0x0c, 0x64, 0x61, 0x74, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x12,
	0x1e, 0x0a, 0x0a, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0a, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x49, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x88, 0x01, 0x0a, 0x0e, 0x41, 0x64,
	0x64, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09,
	0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x61,
	0x6c, 0x65, 0x6e, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a,
	0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x11, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x41, 0x6e, 0x61, 0x6c, 0x79,
	0x73, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x8b, 0x01, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a,
	0x09, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74,
	0x61, 0x6c, 0x65, 0x6e, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0a, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x32, 0x0a, 0x0e, 0x44,
	0x65, 0x6c, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x11, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x32, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x65, 0x6c,
	0x6f, 0x70, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x61,
	0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x08, 0x61, 0x6e, 0x61,
	0x6c, 0x79, 0x73, 0x69, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62,
	0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x08, 0x61, 0x6e, 0x61, 0x6c, 0x79,
	0x73, 0x69, 0x73, 0x32, 0xf3, 0x01, 0x0a, 0x08, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73,
	0x12, 0x36, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x12,
	0x12, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x6e, 0x61, 0x6c,
	0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x61,
	0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0b, 0x44, 0x65, 0x6c,
	0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65,
	0x6c, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70,
	0x62, 0x2e, 0x44, 0x65, 0x6c, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x36, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73,
	0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x61,
	0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_analysis_proto_rawDescOnce sync.Once
	file_analysis_proto_rawDescData = file_analysis_proto_rawDesc
)

func file_analysis_proto_rawDescGZIP() []byte {
	file_analysis_proto_rawDescOnce.Do(func() {
		file_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(file_analysis_proto_rawDescData)
	})
	return file_analysis_proto_rawDescData
}

var file_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_analysis_proto_goTypes = []any{
	(*Analysis)(nil),           // 0: pb.Analysis
	(*AddAnalysisReq)(nil),     // 1: pb.AddAnalysisReq
	(*AddAnalysisResp)(nil),    // 2: pb.AddAnalysisResp
	(*UpdateAnalysisReq)(nil),  // 3: pb.UpdateAnalysisReq
	(*UpdateAnalysisResp)(nil), // 4: pb.UpdateAnalysisResp
	(*DelAnalysisReq)(nil),     // 5: pb.DelAnalysisReq
	(*DelAnalysisResp)(nil),    // 6: pb.DelAnalysisResp
	(*GetAnalysisReq)(nil),     // 7: pb.GetAnalysisReq
	(*GetAnalysisResp)(nil),    // 8: pb.GetAnalysisResp
}
var file_analysis_proto_depIdxs = []int32{
	0, // 0: pb.GetAnalysisResp.analysis:type_name -> pb.Analysis
	1, // 1: pb.analysis.AddAnalysis:input_type -> pb.AddAnalysisReq
	3, // 2: pb.analysis.UpdateAnalysis:input_type -> pb.UpdateAnalysisReq
	5, // 3: pb.analysis.DelAnalysis:input_type -> pb.DelAnalysisReq
	7, // 4: pb.analysis.GetAnalysis:input_type -> pb.GetAnalysisReq
	2, // 5: pb.analysis.AddAnalysis:output_type -> pb.AddAnalysisResp
	4, // 6: pb.analysis.UpdateAnalysis:output_type -> pb.UpdateAnalysisResp
	6, // 7: pb.analysis.DelAnalysis:output_type -> pb.DelAnalysisResp
	8, // 8: pb.analysis.GetAnalysis:output_type -> pb.GetAnalysisResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_analysis_proto_init() }
func file_analysis_proto_init() {
	if File_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_analysis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analysis_proto_goTypes,
		DependencyIndexes: file_analysis_proto_depIdxs,
		MessageInfos:      file_analysis_proto_msgTypes,
	}.Build()
	File_analysis_proto = out.File
	file_analysis_proto_rawDesc = nil
	file_analysis_proto_goTypes = nil
	file_analysis_proto_depIdxs = nil
}
