/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UUsernameImport } from './routes/u_.$username'

// Create Virtual Routes

const RankLazyImport = createFileRoute('/rank')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const RankLazyRoute = RankLazyImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/rank.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const UUsernameRoute = UUsernameImport.update({
  id: '/u_/$username',
  path: '/u/$username',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/u_.$username.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/rank': {
      id: '/rank'
      path: '/rank'
      fullPath: '/rank'
      preLoaderRoute: typeof RankLazyImport
      parentRoute: typeof rootRoute
    }
    '/u_/$username': {
      id: '/u_/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/rank': typeof RankLazyRoute
  '/u/$username': typeof UUsernameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/rank': typeof RankLazyRoute
  '/u/$username': typeof UUsernameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/rank': typeof RankLazyRoute
  '/u_/$username': typeof UUsernameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rank' | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rank' | '/u/$username'
  id: '__root__' | '/' | '/rank' | '/u_/$username'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  RankLazyRoute: typeof RankLazyRoute
  UUsernameRoute: typeof UUsernameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  RankLazyRoute: RankLazyRoute,
  UUsernameRoute: UUsernameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/rank",
        "/u_/$username"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/rank": {
      "filePath": "rank.lazy.tsx"
    },
    "/u_/$username": {
      "filePath": "u_.$username.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
