Name: analysis.api
Host: 0.0.0.0
Port: 3005
TimeOut: 300000

Log:
  ServiceName: analysis.api
  Mode: file
  Encoding: json
  Path: logs/analysis_api/

DB:
  DataSource: postgres://pulse:youguesswhatnobodyknows@postgres:5432/pulse?sslmode=disable
Cache:
  - Host: redis:6379
    Pass:

Redis:
  Host: redis:6379
  Type: node
  Pass:

DeveloperRpcConf:
  Target: consul://consul:8500/developer.rpc?wait=14s
  Timeout: 30000

RelationRpcConf:
  Target: consul://consul:8500/relation.rpc?wait=14s
  Timeout: 180000

ContributionRpcConf:
  Target: consul://consul:8500/contribution.rpc?wait=14s
  Timeout: 300000

RepoRpcConf:
  Target: consul://consul:8500/repo.rpc?wait=14s
  Timeout: 30000

AnalysisRpcConf:
  Target: consul://consul:8500/analysis.rpc?wait=14s
  Timeout: 180000

AsynqRedisConf:
  Addr: redis:6379
  Password:
  DB: 0