Name: analysis.rpc
ListenOn: 0.0.0.0:2005
Timeout: 180000

Log:
  ServiceName: analysis.rpc
  Mode: file
  Encoding: json
  Path: logs/analysis_rpc/

Consul:
  Host: consul:8500 # consul endpoint
  Token:
  Key: analysis.rpc # service name registered to Consul
  Meta:
    Protocol: grpc
  Tag:
    - tag
    - rpc

DeveloperRpcConf:
  Target: consul://consul:8500/developer.rpc?wait=14s
  Timeout: 30000

RelationRpcConf:
  Target: consul://consul:8500/relation.rpc?wait=14s
  Timeout: 180000

ContributionRpcConf:
  Target: consul://consul:8500/contribution.rpc?wait=14s
  Timeout: 300000

RepoRpcConf:
  Target: consul://consul:8500/repo.rpc?wait=14s
  Timeout: 30000

RedisConf:
  Host: redis:6379
  Type: node
  Pass:

DB:
  DataSource: postgres://pulse:youguesswhatnobodyknows@postgres:5432/pulse?sslmode=disable
Cache:
  - Host: redis:6379
    Pass:

SparkModelConf:
  Url: https://spark-api-open.xf-yun.com/v1/chat/completions
  APIPassword: fPXYVCkCeBnqSvEVcFZF:FNtNczoVCwNVkHAgxNJE
  MaxTokens: 1000
  TopK: 4
  Temperature: 0.5
  Model: generalv3.5
  