Name: Developer
Host: 0.0.0.0
Port: 3001
Timeout: 30000

Log:
  ServiceName: developer.api
  Mode: file
  Encoding: json
  Path: logs/developer_api/
  
DB:
  DataSource: postgres://pulse:youguesswhatnobodyknows@postgres:5432/pulse?sslmode=disable
Cache:
  - Host: redis:6379
    Pass:

DeveloperRpcConf:
  Target: consul://consul:8500/developer.rpc?wait=14s
  Timeout: 30000

AsynqRedisConf:
    Addr: redis:6379
    Password:
    DB: 0