Name: repo.rpc
ListenOn: 0.0.0.0:2002
Timeout: 30000

Log:
  ServiceName: repo.rpc
  Mode: file
  Encoding: json
  Path: logs/repo_rpc/

Consul:
  Host: consul:8500
  Token:
  Key: repo.rpc
  Meta:
    Protocol: grpc
  Tag:
    - tag
    - rpc

Redis:
  Host: redis:6379
  Type: node
  Pass:
  Key: repo-rpc

DB:
  DataSource: postgres://pulse:youguesswhatnobodyknows@postgres:5432/pulse?sslmode=disable
Cache:
  - Host: redis:6379
    Pass:

KqRepoUpdateConsumerConf:
  Name: repo-update-consumer
  Brokers:
    - kafka:9092
  Group: repo
  Topic: repo-update