// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: idGen.proto

package idgen

import (
	"context"

	"github.com/ShellWen/GitPulse/idgen/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetIdReq  = pb.GetIdReq
	GetIdResp = pb.GetIdResp

	IdGen interface {
		GetId(ctx context.Context, in *GetIdReq, opts ...grpc.CallOption) (*GetIdResp, error)
	}

	defaultIdGen struct {
		cli zrpc.Client
	}
)

func NewIdGen(cli zrpc.Client) IdGen {
	return &defaultIdGen{
		cli: cli,
	}
}

func (m *defaultIdGen) GetId(ctx context.Context, in *GetIdReq, opts ...grpc.CallOption) (*GetIdResp, error) {
	client := pb.NewIdGenClient(m.cli.Conn())
	return client.GetId(ctx, in, opts...)
}
