// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: developer.proto

package server

import (
	"context"

	"github.com/ShellWen/GitPulse/developer/cmd/rpc/internal/logic"
	"github.com/ShellWen/GitPulse/developer/cmd/rpc/internal/svc"
	"github.com/ShellWen/GitPulse/developer/cmd/rpc/pb"
)

type DeveloperServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedDeveloperServer
}

func NewDeveloperServer(svcCtx *svc.ServiceContext) *DeveloperServer {
	return &DeveloperServer{
		svcCtx: svcCtx,
	}
}

// -----------------------developer-----------------------
func (s *DeveloperServer) AddDeveloper(ctx context.Context, in *pb.AddDeveloperReq) (*pb.AddDeveloperResp, error) {
	l := logic.NewAddDeveloperLogic(ctx, s.svcCtx)
	return l.AddDeveloper(in)
}

func (s *DeveloperServer) UpdateDeveloper(ctx context.Context, in *pb.UpdateDeveloperReq) (*pb.UpdateDeveloperResp, error) {
	l := logic.NewUpdateDeveloperLogic(ctx, s.svcCtx)
	return l.UpdateDeveloper(in)
}

func (s *DeveloperServer) DelDeveloperById(ctx context.Context, in *pb.DelDeveloperByIdReq) (*pb.DelDeveloperByIdResp, error) {
	l := logic.NewDelDeveloperByIdLogic(ctx, s.svcCtx)
	return l.DelDeveloperById(in)
}

func (s *DeveloperServer) DelDeveloperByLogin(ctx context.Context, in *pb.DelDeveloperByLoginReq) (*pb.DelDeveloperByLoginResp, error) {
	l := logic.NewDelDeveloperByLoginLogic(ctx, s.svcCtx)
	return l.DelDeveloperByLogin(in)
}

func (s *DeveloperServer) GetDeveloperById(ctx context.Context, in *pb.GetDeveloperByIdReq) (*pb.GetDeveloperByIdResp, error) {
	l := logic.NewGetDeveloperByIdLogic(ctx, s.svcCtx)
	return l.GetDeveloperById(in)
}

func (s *DeveloperServer) GetDeveloperByLogin(ctx context.Context, in *pb.GetDeveloperByLoginReq) (*pb.GetDeveloperByLoginResp, error) {
	l := logic.NewGetDeveloperByLoginLogic(ctx, s.svcCtx)
	return l.GetDeveloperByLogin(in)
}

func (s *DeveloperServer) BlockUntilDeveloperUpdated(ctx context.Context, in *pb.BlockUntilDeveloperUpdatedReq) (*pb.BlockUntilDeveloperUpdatedResp, error) {
	l := logic.NewBlockUntilDeveloperUpdatedLogic(ctx, s.svcCtx)
	return l.BlockUntilDeveloperUpdated(in)
}
