// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"
	"time"

	developer "github.com/ShellWen/GitPulse/developer/cmd/api/internal/handler/developer"
	"github.com/ShellWen/GitPulse/developer/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:login",
				Handler: developer.GetDeveloperHandler(serverCtx),
			},
		},
		rest.WithPrefix("/developers"),
		rest.WithTimeout(10000*time.Millisecond),
	)
}
