// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	commentOfUserUpdatedAtFieldNames          = builder.RawFieldNames(&CommentOfUserUpdatedAt{}, true)
	commentOfUserUpdatedAtRows                = strings.Join(commentOfUserUpdatedAtFieldNames, ",")
	commentOfUserUpdatedAtRowsExpectAutoSet   = strings.Join(stringx.Remove(commentOfUserUpdatedAtFieldNames, "data_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	commentOfUserUpdatedAtRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(commentOfUserUpdatedAtFieldNames, "data_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cacheContributionCommentOfUserUpdatedAtDataIdPrefix      = "cache:contribution:commentOfUserUpdatedAt:dataId:"
	cacheContributionCommentOfUserUpdatedAtDeveloperIdPrefix = "cache:contribution:commentOfUserUpdatedAt:developerId:"
)

type (
	commentOfUserUpdatedAtModel interface {
		Insert(ctx context.Context, data *CommentOfUserUpdatedAt) (sql.Result, error)
		FindOne(ctx context.Context, dataId int64) (*CommentOfUserUpdatedAt, error)
		FindOneByDeveloperId(ctx context.Context, developerId int64) (*CommentOfUserUpdatedAt, error)
		Update(ctx context.Context, data *CommentOfUserUpdatedAt) error
		Delete(ctx context.Context, dataId int64) error
	}

	defaultCommentOfUserUpdatedAtModel struct {
		sqlc.CachedConn
		table string
	}

	CommentOfUserUpdatedAt struct {
		DataId      int64     `db:"data_id"`
		UpdatedAt   time.Time `db:"updated_at"`
		DeveloperId int64     `db:"developer_id"`
	}
)

func newCommentOfUserUpdatedAtModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCommentOfUserUpdatedAtModel {
	return &defaultCommentOfUserUpdatedAtModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"contribution"."comment_of_user_updated_at"`,
	}
}

func (m *defaultCommentOfUserUpdatedAtModel) Delete(ctx context.Context, dataId int64) error {
	data, err := m.FindOne(ctx, dataId)
	if err != nil {
		return err
	}

	contributionCommentOfUserUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheContributionCommentOfUserUpdatedAtDataIdPrefix, dataId)
	contributionCommentOfUserUpdatedAtDeveloperIdKey := fmt.Sprintf("%s%v", cacheContributionCommentOfUserUpdatedAtDeveloperIdPrefix, data.DeveloperId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where data_id = $1", m.table)
		return conn.ExecCtx(ctx, query, dataId)
	}, contributionCommentOfUserUpdatedAtDataIdKey, contributionCommentOfUserUpdatedAtDeveloperIdKey)
	return err
}

func (m *defaultCommentOfUserUpdatedAtModel) FindOne(ctx context.Context, dataId int64) (*CommentOfUserUpdatedAt, error) {
	contributionCommentOfUserUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheContributionCommentOfUserUpdatedAtDataIdPrefix, dataId)
	var resp CommentOfUserUpdatedAt
	err := m.QueryRowCtx(ctx, &resp, contributionCommentOfUserUpdatedAtDataIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where data_id = $1 limit 1", commentOfUserUpdatedAtRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dataId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentOfUserUpdatedAtModel) FindOneByDeveloperId(ctx context.Context, developerId int64) (*CommentOfUserUpdatedAt, error) {
	contributionCommentOfUserUpdatedAtDeveloperIdKey := fmt.Sprintf("%s%v", cacheContributionCommentOfUserUpdatedAtDeveloperIdPrefix, developerId)
	var resp CommentOfUserUpdatedAt
	err := m.QueryRowIndexCtx(ctx, &resp, contributionCommentOfUserUpdatedAtDeveloperIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where developer_id = $1 limit 1", commentOfUserUpdatedAtRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, developerId); err != nil {
			return nil, err
		}
		return resp.DataId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentOfUserUpdatedAtModel) Insert(ctx context.Context, data *CommentOfUserUpdatedAt) (sql.Result, error) {
	contributionCommentOfUserUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheContributionCommentOfUserUpdatedAtDataIdPrefix, data.DataId)
	contributionCommentOfUserUpdatedAtDeveloperIdKey := fmt.Sprintf("%s%v", cacheContributionCommentOfUserUpdatedAtDeveloperIdPrefix, data.DeveloperId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1)", m.table, commentOfUserUpdatedAtRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DeveloperId)
	}, contributionCommentOfUserUpdatedAtDataIdKey, contributionCommentOfUserUpdatedAtDeveloperIdKey)
	return ret, err
}

func (m *defaultCommentOfUserUpdatedAtModel) Update(ctx context.Context, newData *CommentOfUserUpdatedAt) error {
	data, err := m.FindOne(ctx, newData.DataId)
	if err != nil {
		return err
	}

	contributionCommentOfUserUpdatedAtDataIdKey := fmt.Sprintf("%s%v", cacheContributionCommentOfUserUpdatedAtDataIdPrefix, data.DataId)
	contributionCommentOfUserUpdatedAtDeveloperIdKey := fmt.Sprintf("%s%v", cacheContributionCommentOfUserUpdatedAtDeveloperIdPrefix, data.DeveloperId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where data_id = $1", m.table, commentOfUserUpdatedAtRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DataId, newData.DeveloperId)
	}, contributionCommentOfUserUpdatedAtDataIdKey, contributionCommentOfUserUpdatedAtDeveloperIdKey)
	return err
}

func (m *defaultCommentOfUserUpdatedAtModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheContributionCommentOfUserUpdatedAtDataIdPrefix, primary)
}

func (m *defaultCommentOfUserUpdatedAtModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where data_id = $1 limit 1", commentOfUserUpdatedAtRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCommentOfUserUpdatedAtModel) tableName() string {
	return m.table
}
